/* test_erp_core.c - ERP Core Test Suite (15 tests, L1-L9 coverage) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include "erp_core.h"

#define AF(a,b) do{float _a=(a),_b=(b); if(fabsf(_a-_b)>0.01f){fprintf(stderr,"FAIL %.4f!=%.4f\n",_a,_b);assert(0);}}while(0)

int test_erp_suite(void) {
  printf("  Running ERP tests...\n");
  /*1*/{MENT_ERPInstance*e=ment_erp_create("T","TC");assert(e);assert(e->num_accounts>=7);ment_erp_destroy(e);ment_erp_destroy(NULL);}
  /*2*/{MENT_ERPInstance*e=ment_erp_create("T","TC");assert(ment_erp_setup_fiscal_year(e,2025,1735689600)==0);assert(e->num_periods==13);assert(ment_erp_close_period(e,1)==0);assert(e->periods[0].is_closed);ment_erp_destroy(e);}
  /*3*/{MENT_ERPInstance*e=ment_erp_create("T","TC");int c=ment_erp_add_account(e,"1010","Cash",MENT_ACCTYPE_ASSET,0);int b=ment_erp_add_account(e,"1020","Bank",MENT_ACCTYPE_ASSET,0);int a=ment_erp_add_account(e,"1030","AR",MENT_ACCTYPE_ASSET,0);assert(c>=0);assert(ment_erp_find_account(e,"1010")==c);assert(ment_erp_find_account(e,"9999")==-1);int ch[32];assert(ment_erp_account_children(e,0,ch,32)==3);assert(ment_erp_validate_coa(e));ment_erp_destroy(e);}
  /*4*/{assert(strcmp(ment_acctype_name(MENT_ACCTYPE_ASSET),"Asset")==0);assert(strcmp(ment_acctype_name(MENT_ACCTYPE_LIABILITY),"Liability")==0);assert(ment_acctype_normal_balance(MENT_ACCTYPE_ASSET)==MENT_DEBIT);assert(ment_acctype_normal_balance(MENT_ACCTYPE_REVENUE)==MENT_CREDIT);assert(ment_acctype_normal_balance(MENT_ACCTYPE_EXPENSE)==MENT_DEBIT);}
  /*5*/{MENT_ERPInstance*e=ment_erp_create("T","TC");ment_erp_setup_fiscal_year(e,2025,1735689600);int cash=ment_erp_add_account(e,"1010","Cash",MENT_ACCTYPE_ASSET,0);int sales=ment_erp_add_account(e,"4010","Sales",MENT_ACCTYPE_REVENUE,3);int salex=ment_erp_add_account(e,"5010","Salary",MENT_ACCTYPE_EXPENSE,4);MENT_JournalEntry*j1=ment_erp_create_journal(e,time(0),"INV-001");assert(j1);ment_erp_journal_add_line(j1,cash,10000.0f,MENT_DEBIT,"Cash");ment_erp_journal_add_line(j1,sales,10000.0f,MENT_CREDIT,"Sales");assert(ment_erp_validate_journal(e,j1));assert(ment_erp_post_journal(e,j1)==0);assert(j1->is_posted);AF(ment_erp_account_balance(e,cash,1),10000.0f);AF(ment_erp_account_balance(e,sales,1),10000.0f);MENT_JournalEntry*j2=ment_erp_create_journal(e,time(0),"PAY");ment_erp_journal_add_line(j2,salex,3000.0f,MENT_DEBIT,"Sal");ment_erp_journal_add_line(j2,cash,3000.0f,MENT_CREDIT,"Paid");assert(ment_erp_validate_journal(e,j2));ment_erp_post_journal(e,j2);AF(ment_erp_account_balance(e,cash,1),7000.0f);ment_erp_destroy(e);}
  /*6*/{MENT_ERPInstance*e=ment_erp_create("T","TC");int cash=ment_erp_add_account(e,"1010","Cash",MENT_ACCTYPE_ASSET,0);MENT_JournalEntry*j=ment_erp_create_journal(e,time(0),"BAD");ment_erp_journal_add_line(j,cash,1000.0f,MENT_DEBIT,"Only");assert(!ment_erp_validate_journal(e,j));j->is_posted=true;assert(ment_erp_post_journal(e,j)==-2);MENT_JournalEntry*rev=ment_erp_reverse_journal(e,j);assert(rev);assert(rev->is_reversed);ment_erp_destroy(e);}
  /*7*/{MENT_ERPInstance*e=ment_erp_create("T","TC");int cash=ment_erp_add_account(e,"1010","Cash",MENT_ACCTYPE_ASSET,0);int ap=ment_erp_add_account(e,"2010","AP",MENT_ACCTYPE_LIABILITY,1);int cap=ment_erp_add_account(e,"3010","Capital",MENT_ACCTYPE_EQUITY,2);MENT_JournalEntry*j1=ment_erp_create_journal(e,time(0),"INV");ment_erp_journal_add_line(j1,cash,50000.0f,MENT_DEBIT,"Cash");ment_erp_journal_add_line(j1,cap,50000.0f,MENT_CREDIT,"Cap");ment_erp_post_journal(e,j1);MENT_JournalEntry*j2=ment_erp_create_journal(e,time(0),"LOAN");ment_erp_journal_add_line(j2,cash,20000.0f,MENT_DEBIT,"Cash");ment_erp_journal_add_line(j2,ap,20000.0f,MENT_CREDIT,"Loan");ment_erp_post_journal(e,j2);float A,L,E;ment_erp_balance_sheet(e,1,&A,&L,&E);AF(A,L+E);float D,C;ment_erp_trial_balance(e,1,&D,&C);AF(D,C);ment_erp_destroy(e);}
  /*8*/{MENT_ERPInstance*e=ment_erp_create("T","TC");ment_erp_setup_fiscal_year(e,2025,1735689600);int cash=ment_erp_add_account(e,"1010","Cash",MENT_ACCTYPE_ASSET,0);int sales=ment_erp_add_account(e,"4010","Sales",MENT_ACCTYPE_REVENUE,3);int cogs=ment_erp_add_account(e,"5010","COGS",MENT_ACCTYPE_EXPENSE,4);int rent=ment_erp_add_account(e,"5020","Rent",MENT_ACCTYPE_EXPENSE,4);MENT_JournalEntry*j1=ment_erp_create_journal(e,time(0),"S");ment_erp_journal_add_line(j1,cash,100000.0f,MENT_DEBIT,"Rev");ment_erp_journal_add_line(j1,sales,100000.0f,MENT_CREDIT,"Rev");ment_erp_post_journal(e,j1);MENT_JournalEntry*j2=ment_erp_create_journal(e,time(0),"C");ment_erp_journal_add_line(j2,cogs,60000.0f,MENT_DEBIT,"COGS");ment_erp_journal_add_line(j2,cash,60000.0f,MENT_CREDIT,"Cash");ment_erp_post_journal(e,j2);MENT_JournalEntry*j3=ment_erp_create_journal(e,time(0),"R");ment_erp_journal_add_line(j3,rent,15000.0f,MENT_DEBIT,"Rent");ment_erp_journal_add_line(j3,cash,15000.0f,MENT_CREDIT,"Cash");ment_erp_post_journal(e,j3);float rev,exp,ni;ment_erp_income_statement(e,1,1,&rev,&exp,&ni);AF(rev,100000.0f);AF(exp,75000.0f);AF(ni,25000.0f);ment_erp_destroy(e);}
  /*9*/{MENT_ERPInstance*e=ment_erp_create("G","GC");int eur=ment_erp_add_currency(e,"EUR","Euro",0.92f,"EUR");int jpy=ment_erp_add_currency(e,"JPY","Yen",0.0069f,"JPY");assert(eur>=0&&jpy>=0);assert(e->multi_currency);AF(ment_erp_convert_currency(e,1000.0f,eur),920.0f);float u=ment_erp_convert_currency(e,100000.0f,jpy);assert(u>680.0f&&u<700.0f);AF(ment_erp_convert_currency(e,500.0f,0),500.0f);ment_erp_destroy(e);}
  /*10*/{MENT_ERPInstance*e=ment_erp_create("T","TC");ment_erp_setup_fiscal_year(e,2025,1735689600);int cash=ment_erp_add_account(e,"1010","Cash",MENT_ACCTYPE_ASSET,0);int sales=ment_erp_add_account(e,"4010","Sales",MENT_ACCTYPE_REVENUE,3);MENT_JournalEntry*o=ment_erp_create_journal(e,time(0),"ORIG");ment_erp_journal_add_line(o,cash,5000.0f,MENT_DEBIT,"Cash");ment_erp_journal_add_line(o,sales,5000.0f,MENT_CREDIT,"Sales");ment_erp_post_journal(e,o);MENT_JournalEntry*r=ment_erp_reverse_journal(e,o);assert(r);assert(r->is_reversed);assert(ment_erp_validate_journal(e,r));ment_erp_post_journal(e,r);AF(ment_erp_account_balance(e,cash,1),0.0f);ment_erp_destroy(e);}
  /*11*/{MENT_ERPInstance*e=ment_erp_create("T","TC");ment_erp_setup_fiscal_year(e,2025,1735689600);int cash=ment_erp_add_account(e,"1010","Cash",MENT_ACCTYPE_ASSET,0);int sales=ment_erp_add_account(e,"4010","Sales",MENT_ACCTYPE_REVENUE,3);int i;for(i=0;i<3;i++){MENT_JournalEntry*j=ment_erp_create_journal(e,time(0),"S");ment_erp_journal_add_line(j,cash,(float)(1000*(i+1)),MENT_DEBIT,"Cash");ment_erp_journal_add_line(j,sales,(float)(1000*(i+1)),MENT_CREDIT,"Sales");ment_erp_post_journal(e,j);}int idx[32];assert(ment_erp_account_transactions(e,cash,1,1,idx,32)==3);ment_erp_destroy(e);}
  /*12*/{assert(ment_erp_create(NULL,"T")==NULL);assert(ment_acctype_name(999)!=NULL);MENT_ERPInstance*e=ment_erp_create("T","TC");assert(ment_erp_add_account(NULL,"A","N",MENT_ACCTYPE_ASSET,0)==-1);assert(ment_erp_add_account(e,NULL,"N",MENT_ACCTYPE_ASSET,0)==-1);assert(ment_erp_find_account(NULL,"A")==-1);assert(!ment_erp_validate_coa(NULL));assert(ment_erp_create_journal(NULL,time(0),"R")==NULL);assert(!ment_erp_validate_journal(NULL,NULL));assert(ment_erp_post_journal(NULL,NULL)==-1);assert(ment_erp_account_balance(NULL,0,1)==0.0f);assert(ment_erp_balance_sheet(NULL,1,NULL,NULL,NULL)==-1);assert(ment_erp_income_statement(NULL,1,1,NULL,NULL,NULL)==-1);assert(ment_erp_account_balance(e,999,1)==0.0f);ment_erp_destroy(e);}
  /*13*/{MENT_ERPInstance*e=ment_erp_create("T","TC");ment_erp_setup_fiscal_year(e,2025,1735689600);int re=ment_erp_add_account(e,"3020","Retained Earnings",MENT_ACCTYPE_EQUITY,2);int cash=ment_erp_add_account(e,"1010","Cash",MENT_ACCTYPE_ASSET,0);int sales=ment_erp_add_account(e,"4010","Sales",MENT_ACCTYPE_REVENUE,3);int exp=ment_erp_add_account(e,"5010","Exp",MENT_ACCTYPE_EXPENSE,4);assert(re>=0);int p;for(p=1;p<=3;p++){MENT_JournalEntry*j=ment_erp_create_journal(e,time(0),"M");j->fiscal_period=p;ment_erp_journal_add_line(j,cash,5000.0f,MENT_DEBIT,"C");ment_erp_journal_add_line(j,sales,5000.0f,MENT_CREDIT,"R");ment_erp_journal_add_line(j,exp,2000.0f,MENT_DEBIT,"E");ment_erp_journal_add_line(j,cash,2000.0f,MENT_CREDIT,"P");ment_erp_post_journal(e,j);}assert(ment_erp_period_close(e,3)==0);assert(e->periods[2].is_closed);ment_erp_destroy(e);}
  /*14*/{MENT_ERPInstance*par=ment_erp_create("P","PC");ment_erp_setup_fiscal_year(par,2025,1735689600);int pc=ment_erp_add_account(par,"1010","Cash",MENT_ACCTYPE_ASSET,0);int ps=ment_erp_add_account(par,"4010","Sales",MENT_ACCTYPE_REVENUE,3);MENT_ERPInstance*sub=ment_erp_create("S","SC");ment_erp_setup_fiscal_year(sub,2025,1735689600);ment_erp_add_account(sub,"1010","Cash",MENT_ACCTYPE_ASSET,0);ment_erp_add_account(sub,"4010","Sales",MENT_ACCTYPE_REVENUE,3);MENT_JournalEntry*jp=ment_erp_create_journal(par,time(0),"P");ment_erp_journal_add_line(jp,pc,100000.0f,MENT_DEBIT,"Cash");ment_erp_journal_add_line(jp,ps,100000.0f,MENT_CREDIT,"Sales");ment_erp_post_journal(par,jp);MENT_JournalEntry*js=ment_erp_create_journal(sub,time(0),"S");ment_erp_journal_add_line(js,0,50000.0f,MENT_DEBIT,"Cash");ment_erp_journal_add_line(js,1,50000.0f,MENT_CREDIT,"Sales");ment_erp_post_journal(sub,js);MENT_ERPInstance*subs[1]={sub};assert(ment_erp_consolidate(par,subs,1)==0);ment_erp_destroy(sub);ment_erp_destroy(par);}
  /*15*/{MENT_ERPInstance*e=ment_erp_create("T","TC");int cash=ment_erp_add_account(e,"1010","Cash",MENT_ACCTYPE_ASSET,0);int sales=ment_erp_add_account(e,"4010","Sales",MENT_ACCTYPE_REVENUE,3);ment_erp_audit_log(e,"alice","LOGIN","User login",-1,-1);ment_erp_audit_log(e,"alice","CREATE_JOURNAL","JV-000001",0,-1);MENT_JournalEntry*j=ment_erp_create_journal(e,time(0),"TEST");ment_erp_journal_add_line(j,cash,1000.0f,MENT_DEBIT,"Test");ment_erp_journal_add_line(j,sales,1000.0f,MENT_CREDIT,"Test");ment_erp_post_journal(e,j);MENT_AuditEntry results[64];time_t from=time(0)-86400;time_t to=time(0)+86400;int n=ment_erp_audit_query(e,from,to,results,64);assert(n>0);assert(ment_erp_audit_verify(e));ment_erp_destroy(e);}
  printf("  ERP: 15 tests passed\n");
  return 0;
}
